[Add]first submit anyka AK3918 code
aws-samples/amazon-kinesis-video-streams-media-interface pull request #70
Opened 2022-09-09 06:27 UTC by jmlxgll

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-09-09 07:08 UTC, codingspirit requested changes

2022-09-09 07:08 UTC, codingspirit commented on 3rdparty/AK3918/ak_platform_app.h
> +#ifndef _AK_PLATFORM_APP_H
Since the coding guide line we are using is inconsistent, we suggest to exclude SoC dependencies out of source code structure. Instructions for customers about how to import  SoC dependencies could be mentioned in [3rdparty/README.md](https://github.com/aws-samples/amazon-kinesis-video-streams-media-interface/blob/main/3rdparty/README.md).

2022-09-09 07:08 UTC, codingspirit commented on source/AK3918/AK3918VideoCapturer.c
> +#define FRAME_FILE_PATH_FORMAT_H264 "/mnt/web/amazon-kinesis-video-streams-media-interface-main/resources/frames/h264/frame-%03d" FRAME_FILE_POSTFIX_H264
Why it's reading from dummy frames?

2022-09-09 07:08 UTC, codingspirit commented on source/AK3918/AK3918AudioPlayer.c
> +    LOG("FILE AudioPlayer is not implemented yet");
Does AK3918 has supports for speaker? Two-ways realtime communication is a very important feature.

2022-09-19 09:18 UTC, codingspirit requested changes

2022-09-19 09:18 UTC, codingspirit commented on source/AK3918/AK3918VideoCapturer.c
> +#define  debug_here printf("111111 %s:%d \n",__FUNCTION__,__LINE__);
Please remove unused code here

2022-09-19 09:18 UTC, codingspirit commented on source/AK3918/AK3918VideoCapturer.c
> +    char* framePathFormat;
Why `framePathFormat` was included here?

2022-09-19 09:18 UTC, codingspirit commented on source/AK3918/AK3918VideoCapturer.c
> +    printf("1111111 %s 11111111 %d  iret:    %d\n",__FUNCTION__,__LINE__,iret);
Please remove debugging code

2022-09-19 09:18 UTC, codingspirit commented on source/AK3918/AK3918VideoCapturer.c
> +
unexpected line break

2022-09-19 09:18 UTC, codingspirit commented on source/AK3918/AK3918VideoCapturer.c
> +
unexpected line break

2022-09-19 09:18 UTC, codingspirit commented on source/AK3918/AK3918VideoCapturer.c
> +
unexpected line break

2022-09-19 09:18 UTC, codingspirit commented on source/AK3918/AK3918VideoCapturer.c
> +        //printf("1111111 %s 11111111 %d  iret:    %d\n",__FUNCTION__,__LINE__,iRet);
remove unused code

2022-09-19 09:18 UTC, codingspirit commented on source/AK3918/AK3918VideoCapturer.c
> +        int iRet = AA_LS_GetFrame(0,    AA_LS_STREAM_VIDEO, AK3918Handle->nVideoHandle, &frame);
There is an unexpected tab before `AA_LS_STREAM_VIDEO`

2022-09-19 09:18 UTC, codingspirit commented on source/AK3918/AK3918VideoCapturer.c
> +                	printf("Getframe  : recv a frame((%d, %d, %d) \n",frame.uiDataLen, frame.iWidth, frame.iHeight);
Please use `LOG` here instead of `printf`

2022-09-19 09:18 UTC, codingspirit commented on source/AK3918/AK3918VideoCapturer.c
> +                if(ic++%25 == 0)
Does this mean it supports 25 fps only?

2022-09-19 09:18 UTC, codingspirit commented on source/AK3918/AK3918VideoCapturer.c
> +
unexpected line break

2022-09-19 09:18 UTC, codingspirit commented on source/AK3918/AK3918VideoCapturer.c
> +
unexpected line break

2022-09-19 09:32 UTC, jmlxgll commented on source/AK3918/AK3918VideoCapturer.c
> +                if(ic++%25 == 0)
This is to prevent printing too often

2022-09-20 05:01 UTC, codingspirit requested changes

2022-09-20 05:01 UTC, codingspirit commented on 3rdparty/README.md
> +```
Suggest to add a `AK3918/` here:
```
AK3918/
├── framework
│   ├── include
│   └── lib
├── lib
│   ├── dynamic
│   └── static
└── platform
    ├── include
    ├── include_3rd
    ├── lib
    └── sample
```

2022-09-27 07:05 UTC, merged