support SV82x platform
aws-samples/amazon-kinesis-video-streams-media-interface pull request #84
Opened 2022-10-26 12:49 UTC by EndlessVoid

Signed-off-by: zhouhuo <kael.chou@eeasytech.com>

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-10-26 12:50 UTC, EndlessVoid commented
support  SV82x platform from Eeasytech

2022-10-27 01:49 UTC, codingspirit requested changes

2022-10-27 01:49 UTC, codingspirit commented on 3rdparty/SV82x/common/sample_comm_ippu.c
> + * Copyright (C) 2020-2021, LomboTech Co.Ltd. All rights reserved.
What's the license of those files? Are those files contributed by Eeasy?

2022-10-27 01:49 UTC, codingspirit commented on source/SV82x/SV82xAudioCapturer.c
> +#include <stdlib.h>
Files under *amazon-kinesis-video-streams-media-interface/source/* should be licensed under Apache 2.0. You may copy those license header from other files.

2022-10-27 01:49 UTC, codingspirit commented on source/SV82x/SV82xAudioCapturer.c
> +	printf("audioCapturerCreate ############################\n");
Use `LOG` instead of `printf`

2022-10-27 01:49 UTC, codingspirit commented on source/SV82x/SV82xAudioCapturer.c
> +		goto AIAENC_ERR2;
Please avoid to use `goto`

2022-10-27 01:49 UTC, codingspirit commented on source/SV82x/SV82xAudioCapturer.c
> +			EI_TRACE_AUDIO(EI_DBG_ERR, "SAMPLE_COMM_AUDIO_DestroyTrdAencAdec failed, s32Ret=%d\n", s32Ret);
`LOG`

2022-10-27 01:49 UTC, codingspirit commented on source/SV82x/SV82xAudioCapturer.c
> +		printf("SAMPLE_COMM_AUDIO_StopAi failed %x\n", s32Ret);
`LOG`

2022-10-27 01:49 UTC, codingspirit commented on source/SV82x/SV82xAudioCapturer.c
> +	// Now implementation supports raw PCM, G.711 ALAW and ULAW, MONO, 8k/16k, 16 bits
I can see `AAC` related code below - Do you forget to add AAC into capability?

2022-10-27 01:49 UTC, codingspirit commented on source/SV82x/SV82xAudioPlayer.c
> +		goto ADECAO_ERR2;
remove `goto`

2022-11-11 06:29 UTC, codingspirit approved these changes

2022-11-11 06:31 UTC, merged